{{- range $name, $component := .Values.components }}
{{- with $component.http }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ $name }}
spec:
  selector:
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/component: {{ $name }}
  ports:
    - port: {{ .port }}
      targetPort: {{ .port }}
{{- end }}
{{- end }}
