apiVersion: v1
kind: Namespace
metadata:
  name: team-alpha-staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-alpha-production
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-beta-staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-beta-production
